## CodexDefs.gd — Diccionario central del Compendio (Codex).
## Define todas las entradas: categoría, texto (ES/EN), condición de desbloqueo.
## La condición usa los mismos tipos que LegacyManager._check_condition().
class_name CodexDefs

const CATEGORIES: Array = ["mecanicas", "simbolos", "mutaciones", "rutas", "arbol_oscuro", "finales", "cruces", "cosmica", "valores"]

const CATEGORY_NAMES: Dictionary = {
	"mecanicas":    {"es": "Mecánicas", "en": "Mechanics"},
	"simbolos":     {"es": "Símbolos", "en": "Symbols"},
	"mutaciones":   {"es": "Mutaciones", "en": "Mutations"},
	"rutas":        {"es": "Rutas", "en": "Routes"},
	"arbol_oscuro": {"es": "Árbol Oscuro", "en": "Dark Tree"},
	"finales":      {"es": "Finales", "en": "Endings"},
	"cruces":       {"es": "Cruces de Legado", "en": "Legacy Crosses"},
	"cosmica":      {"es": "Capa Cósmica", "en": "Cosmic Layer"},
	"valores":      {"es": "Valores", "en": "Reference"},
}

# Cada entrada: cat, name_es, name_en, body_es, body_en, unlock (tipo LegacyManager._check_condition)
const ENTRIES: Dictionary = {

	# ── MECÁNICAS ────────────────────────────────────────────────────────────
	"epsilon": {
		"cat": "mecanicas",
		"name_es": "Epsilon (ε)", "name_en": "Epsilon (ε)",
		"body_es": (
			"ε es la eficiencia estructural del sistema. Comienza en 0 y crece con upgrades estructurales (Auto, Trueque, etc.).\n"
			+ "Afecta directamente la producción pasiva y el multiplicador de click.\n"
			+ "Persiste levemente entre ciclos (ε_persiste) si se compraron buffs adecuados."
		),
		"body_en": (
			"ε is structural efficiency. Starts at 0 and grows with structural upgrades (Auto, Trueque, etc.).\n"
			+ "Directly affects passive income and click multiplier.\n"
			+ "Slightly carries over between cycles (ε_persist) with the right legacy buffs."
		),
		"unlock": {"type": "always"},
	},
	"biomasa": {
		"cat": "mecanicas",
		"name_es": "Biomasa", "name_en": "Biomass",
		"body_es": (
			"La biomasa representa la vitalidad del organismo. Se acumula cuando hay hifas activas y nutrientes disponibles.\n"
			+ "Tiene un límite blando de 8 en runs normales (PRE_HOMEOSTASIS_CAP); las rutas avanzadas lo eliminan o lo amplían.\n"
			+ "Muchos finales requieren cierta biomasa como condición."
		),
		"body_en": (
			"Biomass represents the organism's vitality. Accumulates when hyphae are active and nutrients are available.\n"
			+ "Has a soft cap of 8 in normal runs (PRE_HOMEOSTASIS_CAP); advanced routes remove or raise it.\n"
			+ "Many endings require a minimum biomass."
		),
		"unlock": {"type": "always"},
	},
	"nutrientes": {
		"cat": "mecanicas",
		"name_es": "Nutrientes", "name_en": "Nutrients",
		"body_es": (
			"Se generan absorbiendo estrés (ε). Cumplen DOS funciones simultáneas:\n\n"
			+ "[b]1. Combustible de biomasa[/b] — junto a las hifas hacen crecer la biomasa. Aporte ≈ hifas · √nutrientes · 0.02 por segundo. [b]Sin hifas activas no producen biomasa[/b], por más nutrientes que tengas.\n\n"
			+ "[b]2. Descuento de upgrades[/b] — cada 50 acumulados restan 15% al costo, hasta −45% a 150.\n\n"
			+ "El header muestra ambos efectos en vivo (−% upg · + bio/s). Buffs como Catabolismo Heredado (NG+) o Reserva Nutricia (Cósmico) los dan al inicio de la run."
		),
		"body_en": (
			"Generated by absorbing stress (ε). They serve TWO functions at once:\n\n"
			+ "[b]1. Biomass fuel[/b] — together with hyphae they grow biomass. Rate ≈ hyphae · √nutrients · 0.02 per second. [b]Without active hyphae they produce no biomass[/b], no matter how many you have.\n\n"
			+ "[b]2. Upgrade discount[/b] — every 50 accumulated cut cost by 15%, up to −45% at 150.\n\n"
			+ "The header shows both effects live (−% upg · + bio/s). Buffs like Inherited Catabolism (NG+) or Nutrient Reserve (Cosmic) grant them at the run's start."
		),
		"unlock": {"type": "always"},
		"see_also": ["biomasa", "upgrades_estructura"],
	},
	"esporas": {
		"cat": "mecanicas",
		"name_es": "Esporas y PL", "name_en": "Spores and LP",
		"body_es": (
			"Las esporas se acumulan durante la run y se convierten en PL (Poder Latente) al trascender.\n"
			+ "50 esporas = 1 PL. El PL se gasta en el Banco Genético para comprar mejoras permanentes.\n"
			+ "Ciertas rutas (Esporulación, Panspermia) producen esporas de forma activa."
		),
		"body_en": (
			"Spores accumulate during the run and convert to LP (Latent Power) on transcendence.\n"
			+ "50 spores = 1 LP. LP is spent in the Genetic Bank for permanent upgrades.\n"
			+ "Certain routes (Sporulation, Panspermia) actively generate spores."
		),
		"unlock": {"type": "always"},
	},

	"formula_produccion": {
		"cat": "mecanicas",
		"name_es": "Fórmula de producción", "name_en": "Production formula",
		"body_es": (
			"El ingreso total (∫$) suma tres fuentes, todas escaladas por el factor Λ:\n\n"
			+ "[b]Click[/b] = clicks · a · b · cₙ · μ\n"
			+ "  a = click base · b = multiplicador · cₙ = capital cognitivo · μ = factor complejidad/hongo\n\n"
			+ "[b]Trabajo Manual[/b] (pasivo) = d · md · so · μ · β · (1 + acc·0.05)\n"
			+ "  d = trabajo manual/s · md = ritmo de trabajo · so = especialización (×1.1/nivel)\n"
			+ "  μ = factor complejidad/hongo · β = biomasa beta · acc = niveles de contabilidad\n\n"
			+ "[b]Trueque[/b] (pasivo) = e · me · μ · β · (1 + acc·0.05)\n"
			+ "  e = trueque corregido/s · me = red de intercambio\n"
			+ "  (mismos μ, β y bonus de contabilidad que el Trabajo Manual)\n\n"
			+ "[b]μ (mu)[/b] = factor de complejidad estructural × factor hongo (biomasa). Sube con Capital Cognitivo y biomasa; baja con Homeostasis.\n\n"
			+ "[b]β (beta)[/b] = 1 + log(1 + biomasa) · eficiencia. Sin biomasa vale 1. Con Micelio Resiliente tiene un piso mínimo.\n\n"
			+ "[b]Λ[/b] = producto de todos los multiplicadores activos (legados, buffs cósmicos, mutaciones): Aura Dorada, Eco Primordial, Convergencia Cíclica, Metabolismo Oscuro, etc. Algunos solo se activan en bandas de ε (mg si ε>0.40, ed si ε>0.65).\n\n"
			+ "[i]Activá el Modo Laboratorio (tecla L) para ver el desglose completo en vivo.[/i]"
		),
		"body_en": (
			"Total income (∫$) sums three sources, all scaled by the Λ factor:\n\n"
			+ "[b]Click[/b] = clicks · a · b · cₙ · μ\n"
			+ "  a = base click · b = multiplier · cₙ = cognitive capital · μ = complexity/fungal factor\n\n"
			+ "[b]Manual Labor[/b] (passive) = d · md · so · μ · β · (1 + acc·0.05)\n"
			+ "  d = manual labor/s · md = work rhythm · so = specialization (×1.1/level)\n"
			+ "  μ = complexity/fungal factor · β = biomass beta · acc = accounting levels\n\n"
			+ "[b]Barter[/b] (passive) = e · me · μ · β · (1 + acc·0.05)\n"
			+ "  e = corrected barter/s · me = exchange network\n"
			+ "  (same μ, β and accounting bonus as Manual Labor)\n\n"
			+ "[b]μ (mu)[/b] = structural complexity factor × fungal factor (biomass). Rises with Cognitive Capital and biomass; reduced by Homeostasis.\n\n"
			+ "[b]β (beta)[/b] = 1 + log(1 + biomass) · efficiency. Equals 1 without biomass. With Resilient Mycelium it has a minimum floor.\n\n"
			+ "[b]Λ[/b] = product of all active multipliers (legacies, cosmic buffs, mutations): Golden Aura, Primordial Echo, Cyclic Convergence, Dark Metabolism, etc. Some only activate within ε bands (mg if ε>0.40, ed if ε>0.65).\n\n"
			+ "[i]Toggle Lab Mode (key L) to see the full live breakdown.[/i]"
		),
		"unlock": {"type": "always"},
		"see_also": ["upgrades_estructura", "sym_estructura"],
	},
	"upgrades_estructura": {
		"cat": "mecanicas",
		"name_es": "Upgrades estructurales", "name_en": "Structural upgrades",
		"body_es": (
			"Las mejoras comprables con dinero durante la run:\n\n"
			+ "• [b]Mejorar Click[/b] — sube a (click base) y b (multiplicador)\n"
			+ "• [b]Trabajo Manual[/b] — desbloquea/sube d (ingreso pasivo)\n"
			+ "• [b]Ritmo de Trabajo[/b] — sube md (multiplica el Trabajo Manual)\n"
			+ "• [b]Trueque[/b] — desbloquea/sube e (segunda fuente pasiva)\n"
			+ "• [b]Red de Intercambio[/b] — sube me (multiplica el Trueque)\n"
			+ "• [b]Especialización de Oficio[/b] — ×1.1 por nivel al Trabajo Manual (d·md). No afecta Click ni Trueque\n"
			+ "• [b]Capital Cognitivo[/b] — sube cₙ (μ y complejidad)\n"
			+ "• [b]Memoria Operativa[/b] — sube c₀ (persistencia base, +25%)\n"
			+ "• [b]Contabilidad[/b] — ancla Ω en 0.45, desbloquea la institución y da +5% al ingreso pasivo (TM y Trueque) por nivel\n\n"
			+ "[i]Atajos 1-9 para comprar. En Metabolismo Oscuro las compras se bloquean (salvo sub-rutas).[/i]"
		),
		"body_en": (
			"Upgrades purchasable with money during the run:\n\n"
			+ "• [b]Improve Click[/b] — raises a (base click) and b (multiplier)\n"
			+ "• [b]Manual Labor[/b] — unlocks/raises d (passive income)\n"
			+ "• [b]Work Rhythm[/b] — raises md (multiplies Manual Labor)\n"
			+ "• [b]Barter[/b] — unlocks/raises e (second passive source)\n"
			+ "• [b]Exchange Network[/b] — raises me (multiplies Barter)\n"
			+ "• [b]Trade Specialization[/b] — ×1.1 per level to Manual Labor (d·md). Does not affect Click or Barter\n"
			+ "• [b]Cognitive Capital[/b] — raises cₙ (μ and complexity)\n"
			+ "• [b]Operational Memory[/b] — raises c₀ (base persistence, +25%)\n"
			+ "• [b]Accounting[/b] — anchors Ω at 0.45, unlocks the institution, and adds +5% to passive income (ML and Barter) per level\n\n"
			+ "[i]Hotkeys 1-9 to buy. In Dark Metabolism purchases lock (except sub-routes).[/i]"
		),
		"unlock": {"type": "always"},
		"see_also": ["formula_produccion", "nutrientes"],
	},
	"trascendencia": {
		"cat": "mecanicas",
		"name_es": "Trascendencia", "name_en": "Transcendence",
		"body_es": (
			"El reinicio profundo que abre rutas y capas nuevas. Para trascender necesitás haber cerrado al menos un final de cada una de las tres familias, más PL acumulado:\n\n"
			+ "• [b]Familia ORDEN[/b] — Homeostasis / Allostasis / Homeorresis / Singularidad\n"
			+ "• [b]Familia BIOLOGÍA[/b] — Esporulación / Parasitismo / Simbiosis / Panspermia\n"
			+ "• [b]Familia COLAPSO[/b] — Hiperasimilación / Depredador / Metabolismo Oscuro\n"
			+ "• [b]PL acumulado ≥ 50[/b]\n\n"
			+ "Al trascender ganás Esencia (Ξ) para el Banco Cósmico, subís de Tier (T) y desbloqueás las rutas post-trascendencia para la próxima run."
		),
		"body_en": (
			"The deep reset that opens new routes and layers. To transcend you must have closed at least one ending from each of the three families, plus accumulated LP:\n\n"
			+ "• [b]ORDER family[/b] — Homeostasis / Allostasis / Homeorhesis / Singularity\n"
			+ "• [b]BIOLOGY family[/b] — Sporulation / Parasitism / Symbiosis / Panspermia\n"
			+ "• [b]COLLAPSE family[/b] — Hyperassimilation / Predator / Dark Metabolism\n"
			+ "• [b]Accumulated LP ≥ 50[/b]\n\n"
			+ "On transcending you earn Essence (Ξ) for the Cosmic Bank, rise a Tier (T), and unlock the post-transcendence routes for the next run."
		),
		"unlock": {"type": "always"},
		"see_also": ["sym_meta", "post_tras_routes", "cosmica_intro"],
	},

	"banco_genetico": {
		"cat": "mecanicas",
		"name_es": "Banco Genético", "name_en": "Genetic Bank",
		"body_es": (
			"La capa de mejoras permanentes que se compran con PL (Poder Latente). El PL se gana al cerrar runs: un monto base según la ruta + conversión de esporas (50 esporas = 1 PL).\n\n"
			+ "Los legados se agrupan en categorías:\n"
			+ "• [b]Economía[/b] — descuentos y bonos de ingreso (Deflación, Memoria de Recurso…)\n"
			+ "• [b]Estructura[/b] — escalado y techos (Memoria Estructural, Horizonte Estructural…)\n"
			+ "• [b]Biología[/b] — biomasa e hifas persistentes\n"
			+ "• [b]Conocimiento[/b] — visibilidad, slots y el Historial de Ciclos\n"
			+ "• [b]Ruta[/b] — bonos heredados al haber cerrado ciertos finales\n"
			+ "• [b]NG+[/b] — accesos y permisos del árbol oscuro (tras trascender)\n\n"
			+ "Muchos legados se revelan al cumplir condiciones (cerrar una ruta, alcanzar un pico, trascender). Por encima está el Banco Cósmico, que usa Esencia."
		),
		"body_en": (
			"The permanent upgrade layer bought with LP (Latent Power). LP is earned by closing runs: a base amount per route + spore conversion (50 spores = 1 LP).\n\n"
			+ "Legacies are grouped into categories:\n"
			+ "• [b]Economy[/b] — discounts and income bonuses (Deflation, Resource Memory…)\n"
			+ "• [b]Structure[/b] — scaling and ceilings (Structural Memory, Structural Horizon…)\n"
			+ "• [b]Biology[/b] — persistent biomass and hyphae\n"
			+ "• [b]Knowledge[/b] — visibility, slots and the Cycle History\n"
			+ "• [b]Route[/b] — inherited bonuses from closing certain endings\n"
			+ "• [b]NG+[/b] — dark tree accesses and permits (after transcending)\n\n"
			+ "Many legacies reveal themselves on conditions (closing a route, reaching a peak, transcending). Above it sits the Cosmic Bank, which uses Essence."
		),
		"unlock": {"type": "always"},
		"see_also": ["trascendencia", "sym_meta", "cosmica_intro"],
	},

	"omega": {
		"cat": "mecanicas",
		"name_es": "Omega (Ω) — Orden estructural", "name_en": "Omega (Ω) — Structural order",
		"body_es": (
			"Ω es el índice de estabilidad estructural del sistema. Va de 0 (colapso) a ~1 (orden pleno).\n\n"
			+ "[b]Fórmula:[/b] Ω = 1 / (1 + ε · k_mu · n^0.85)\n"
			+ "  ε = estrés actual · k_mu = resiliencia estructural (sube con upgrades y μ) · n = complejidad efectiva\n\n"
			+ "[b]¿Qué lo baja?[/b]\n"
			+ "• ε alto (el sistema bajo tensión)\n"
			+ "• Muchos upgrades comprados sin Contabilidad (aumentan n)\n"
			+ "• Hiperasimilación (ε artificial multiplicado por biomasa)\n\n"
			+ "[b]¿Qué lo protege?[/b]\n"
			+ "• Contabilidad — reduce n efectivo (−30% por nivel): el único upgrade que baja la complejidad\n"
			+ "• Homeostasis — cap suave de Ω, biomasa y estrés durante el run\n"
			+ "• Allostasis — si Ω cae, puede rebotar: el sistema aprende de la perturbación\n"
			+ "• Homeorresis — bonus temporal de resiliencia para aguantar caídas bruscas\n"
			+ "• Memoria Operativa / Persistencia — Ω persiste levemente entre ciclos\n\n"
			+ "[b]Consecuencias de Ω bajo:[/b]\n"
			+ "• Producción cae (el factor Ω entra en la fórmula de ingreso)\n"
			+ "• Riesgo de activar Depredador de Realidades (crisis profunda)\n"
			+ "• En Necrosis y Omega-Cero: Ω bajo es combustible, no amenaza"
		),
		"body_en": (
			"Ω is the system's structural stability index. Ranges from 0 (collapse) to ~1 (full order).\n\n"
			+ "[b]Formula:[/b] Ω = 1 / (1 + ε · k_mu · n^0.85)\n"
			+ "  ε = current stress · k_mu = structural resilience (rises with upgrades and μ) · n = effective complexity\n\n"
			+ "[b]What lowers it?[/b]\n"
			+ "• High ε (system under tension)\n"
			+ "• Many upgrades bought without Accounting (increase n)\n"
			+ "• Hyperassimilation (ε artificially multiplied by biomass)\n\n"
			+ "[b]What protects it?[/b]\n"
			+ "• Accounting — reduces effective n (−30% per level): the only upgrade that lowers complexity\n"
			+ "• Homeostasis — soft cap on Ω, biomass and stress during the run\n"
			+ "• Allostasis — if Ω drops, it can rebound: the system learns from perturbation\n"
			+ "• Homeorhesis — temporary resilience bonus to weather sudden drops\n"
			+ "• Operational Memory / Persistence — Ω persists slightly between cycles\n\n"
			+ "[b]Consequences of low Ω:[/b]\n"
			+ "• Production drops (Ω factor enters the income formula)\n"
			+ "• Risk of triggering Predator of Realities (deep crisis)\n"
			+ "• In Necrosis and Omega-Zero: low Ω is fuel, not a threat"
		),
		"unlock": {"type": "always"},
		"see_also": ["epsilon", "homeostasis", "allostasis", "homeorhesis"],
	},
	"perturbaciones": {
		"cat": "mecanicas",
		"name_es": "Perturbaciones y eventos", "name_en": "Perturbations & events",
		"body_es": (
			"Eventos que interrumpen la estabilidad durante las runs. Cada fase tiene los suyos:\n\n"
			+ "[b]Colonización (Rama Verde):[/b]\n"
			+ "• Retracción del sustrato — cada 14 s muerde 4–18% de micelio (escala +0.05%/s con el tiempo en fase, cap 18%)\n"
			+ "• La frontera retrocede 2%/s si no clickeás (por encima del piso de 8%)\n\n"
			+ "[b]Primordio (Rama Verde):[/b]\n"
			+ "• Contaminación — cada 6 s daña 14–30 de integridad (escala con maduración) + patea ε +0.16\n"
			+ "• Sobrecalentamiento — si ε > 0.50: drena 4 integridad/s y congela la maduración\n\n"
			+ "[b]Hiperasimilación:[/b]\n"
			+ "• El hongo genera estrés artificial: ε_efectivo = ε × (1 + biomasa × 0.25)\n"
			+ "• Nutrientes se drenan a 25 × exceso por segundo\n\n"
			+ "[b]Metabolismo Oscuro:[/b]\n"
			+ "• Devorado pasivo continuo: el sistema se come sus propios upgrades\n"
			+ "• Timer de inestabilidad en Depredador: cada segundo sin devour acerca el colapso\n\n"
			+ "[i]Contra-jugada universal: Regar (Primordio), clickear el reactor (Colonización), Purgar (Necrosis), botones ±Ω (Remisión).[/i]"
		),
		"body_en": (
			"Events that disrupt stability during runs. Each phase has its own:\n\n"
			+ "[b]Colonization (Green Branch):[/b]\n"
			+ "• Substrate retraction — every 14 s bites 4–18% mycelium (scales +0.05%/s with time in phase, cap 18%)\n"
			+ "• Frontier recedes 2%/s if you don't click (above the 8% floor)\n\n"
			+ "[b]Primordium (Green Branch):[/b]\n"
			+ "• Contamination — every 6 s deals 14–30 integrity damage (scales with maturation) + kicks ε +0.16\n"
			+ "• Overheating — if ε > 0.50: drains 4 integrity/s and freezes maturation\n\n"
			+ "[b]Hyperassimilation:[/b]\n"
			+ "• The fungus generates artificial stress: ε_effective = ε × (1 + biomass × 0.25)\n"
			+ "• Nutrients drain at 25 × excess per second\n\n"
			+ "[b]Dark Metabolism:[/b]\n"
			+ "• Continuous passive devouring: the system eats its own upgrades\n"
			+ "• Instability timer in Predator: each second without a devour nears collapse\n\n"
			+ "[i]Universal counter-play: Water (Primordium), click reactor (Colonization), Purge (Necrosis), ±Ω buttons (Remission).[/i]"
		),
		"unlock": {"type": "transcendence_count", "min": 1},
		"see_also": ["colonizacion_mecanica", "primordio_mecanica", "omega"],
	},

	# ── SÍMBOLOS (glosario de referencia rápida) ─────────────────────────────
	"sym_recursos": {
		"cat": "simbolos",
		"name_es": "Recursos básicos", "name_en": "Core resources",
		"body_es": (
			"[b]ε[/b] (epsilon) — eficiencia estructural del sistema (0 = inactivo)\n"
			+ "[b]Bio[/b] — biomasa, vitalidad del organismo\n"
			+ "[b]Nut[/b] — nutrientes, combustible inmediato de la biomasa\n"
			+ "[b]$[/b] — dinero, moneda de la economía dentro de la run\n"
			+ "[b]Hif[/b] — hifas, filamentos que sostienen el micelio\n"
			+ "[b]Micelio[/b] — red viva (rama biológica)\n"
			+ "[b]Esporas[/b] — se acumulan en la run y se convierten en PL al trascender"
		),
		"body_en": (
			"[b]ε[/b] (epsilon) — structural efficiency of the system (0 = inactive)\n"
			+ "[b]Bio[/b] — biomass, the organism's vitality\n"
			+ "[b]Nut[/b] — nutrients, immediate biomass fuel\n"
			+ "[b]$[/b] — money, the in-run economic currency\n"
			+ "[b]Hyf[/b] — hyphae, filaments sustaining the mycelium\n"
			+ "[b]Mycelium[/b] — living network (biological branch)\n"
			+ "[b]Spores[/b] — accumulate during the run, convert to LP on transcendence"
		),
		"unlock": {"type": "always"},
		"see_also": ["epsilon", "biomasa", "nutrientes", "esporas"],
	},
	"sym_estructura": {
		"cat": "simbolos",
		"name_es": "Estructura y economía", "name_en": "Structure & economy",
		"body_es": (
			"[b]Ω[/b] (omega) — estabilidad estructural (0 = colapso, 1 = estable)\n"
			+ "[b]Estrés[/b] — tensión del sistema; alto estrés acerca al colapso\n"
			+ "[b]c₀[/b] — persistencia base del capital cognitivo\n"
			+ "[b]cₙ[/b] — capital cognitivo actual (escala con upgrades)\n"
			+ "[b]n[/b] — exponente de complejidad acumulada\n"
			+ "[b]μ[/b] (mu) — multiplicador global de producción\n"
			+ "[b]Δ$[/b] — flujo neto de dinero por segundo"
		),
		"body_en": (
			"[b]Ω[/b] (omega) — structural stability (0 = collapse, 1 = stable)\n"
			+ "[b]Stress[/b] — system tension; high stress nears collapse\n"
			+ "[b]c₀[/b] — base persistence of cognitive capital\n"
			+ "[b]cₙ[/b] — current cognitive capital (scales with upgrades)\n"
			+ "[b]n[/b] — accumulated complexity exponent\n"
			+ "[b]μ[/b] (mu) — global production multiplier\n"
			+ "[b]Δ$[/b] — net money flow per second"
		),
		"unlock": {"type": "always"},
		"see_also": ["omega"],
	},
	"sym_meta": {
		"cat": "simbolos",
		"name_es": "Meta-progresión", "name_en": "Meta-progression",
		"body_es": (
			"[b]PL[/b] — Poder Latente; se gana al trascender y se gasta en el Banco Genético\n"
			+ "[b]Ξ[/b] (Esencia) — moneda cósmica; persiste entre trascendencias, alimenta el Banco Cósmico\n"
			+ "[b]Trascendencia (T)[/b] — reinicio profundo que abre rutas y capas nuevas"
		),
		"body_en": (
			"[b]LP[/b] — Latent Power; earned on transcendence, spent in the Genetic Bank\n"
			+ "[b]Ξ[/b] (Essence) — cosmic currency; persists across transcendences, fuels the Cosmic Bank\n"
			+ "[b]Transcendence (T)[/b] — deep reset that opens new routes and layers"
		),
		"unlock": {"type": "always"},
		"see_also": ["esporas", "cosmica_intro"],
	},
	"sym_oscuros": {
		"cat": "simbolos",
		"name_es": "Símbolos oscuros", "name_en": "Dark symbols",
		"body_es": (
			"[b]Φ[/b] (phi) — núcleo de síntesis del Protocolo Omega-Cero; se genera por devour\n"
			+ "[b]Ν[/b] (nu) — Necromasa; economía paralela de Necrosis Controlada\n"
			+ "[b]Θ[/b] (theta) — medidor de sanación de Remisión Metabólica\n"
			+ "[b]Devour[/b] — consumo de un upgrade para liberar energía"
		),
		"body_en": (
			"[b]Φ[/b] (phi) — Omega-Zero Protocol synthesis core; generated per devour\n"
			+ "[b]Ν[/b] (nu) — Necromass; Controlled Necrosis' parallel economy\n"
			+ "[b]Θ[/b] (theta) — Metabolic Remission's healing meter\n"
			+ "[b]Devour[/b] — consuming an upgrade to release energy"
		),
		"unlock": {"type": "transcendence_count", "min": 1},
		"see_also": ["omega_cero", "necrosis", "remision"],
	},

	# ── MUTACIONES ───────────────────────────────────────────────────────────
	# El cuerpo se compone desde claves LORE_<prefix>_* (narrativa + beneficios + contras),
	# ya traducidas EN/ES. unlock = haber cerrado por ese final al menos una vez.
	"homeostasis": {
		"cat": "mutaciones",
		"name_es": "Homeostasis", "name_en": "Homeostasis",
		"lore_prefix": "LORE_HOME",
		"unlock": {"type": "route_closed", "route": "HOMEOSTASIS"},
	},
	"allostasis": {
		"cat": "mutaciones",
		"name_es": "Allostasis", "name_en": "Allostasis",
		"lore_prefix": "LORE_ALOS",
		"unlock": {"type": "route_closed", "route": "ALLOSTASIS"},
	},
	"homeorhesis": {
		"cat": "mutaciones",
		"name_es": "Homeorresis", "name_en": "Homeorhesis",
		"lore_prefix": "LORE_HOMR",
		"unlock": {"type": "route_closed", "route": "HOMEORHESIS"},
	},
	"simbiosis": {
		"cat": "mutaciones",
		"name_es": "Simbiosis Mecánica", "name_en": "Mechanical Symbiosis",
		"lore_prefix": "LORE_SIMB",
		"unlock": {"type": "route_closed", "route": "SIMBIOSIS"},
	},
	"singularidad": {
		"cat": "mutaciones",
		"name_es": "Singularidad", "name_en": "Singularity",
		"lore_prefix": "LORE_SING",
		"unlock": {"type": "route_closed", "route": "SINGULARIDAD"},
	},
	"mente_colmena": {
		"cat": "mutaciones",
		"name_es": "Mente Colmena Distribuida", "name_en": "Distributed Hive Mind",
		"lore_prefix": "LORE_MENTE",
		"unlock": {"type": "route_closed", "route": "MENTE COLMENA DISTRIBUIDA"},
	},
	"esporulacion": {
		"cat": "mutaciones",
		"name_es": "Esporulación", "name_en": "Sporulation",
		"lore_prefix": "LORE_ESPOR",
		"unlock": {"type": "route_closed", "route": "ESPORULACIÓN"},
	},
	"panspermia": {
		"cat": "mutaciones",
		"name_es": "Panspermia Negra", "name_en": "Black Panspermia",
		"lore_prefix": "LORE_PANSP",
		"body_es": (
			"Ruta post-Esporulación (requiere Seta Formada). El hongo eyecta esporas hacia el espacio en una secuencia de pulsos controlada. Anti-AFK: no podés ir ni demasiado lento ni demasiado rápido.\n\n"
			+ "[b]Recursos de lanzamiento:[/b]\n"
			+ "• [b]Carga[/b] — necesitás acumular 100 para alcanzar la velocidad de escape. Decae 7/s (no podés pausar).\n"
			+ "• [b]Calor[/b] — cada eyección suma 25. Disipa 15/s. Si una eyección pasaría de 100 → MISFIRE.\n\n"
			+ "[b]Por cada eyección (click):[/b]\n"
			+ "• +15 carga · +25 calor · −$12.000 · +0.05 ε (estrés del lanzamiento)\n\n"
			+ "[b]Misfire (sobrecarga):[/b]\n"
			+ "• Pierdes 18 de carga. Máx 5 misfires antes de abortar el lanzamiento → Esporulación base sin bonus.\n\n"
			+ "[b]Ritmo óptimo:[/b] eyección → pequeña pausa → eyección. Demasiado rápido → misfire. Demasiado lento → la carga decae y nunca llegás a 100.\n\n"
			+ "[b]Éxito:[/b] Carga ≥ 100 → [b]PANSPERMIA NEGRA[/b] (+10 PL). Requiere Seta Formada para el bonus ×3 de esporas."
		),
		"body_en": (
			"Post-Sporulation route (requires Formed Mushroom). The fungus ejects spores into space in a controlled pulse sequence. Anti-AFK: you can't go too slow or too fast.\n\n"
			+ "[b]Launch resources:[/b]\n"
			+ "• [b]Charge[/b] — you need to accumulate 100 to reach escape velocity. Decays 7/s (you can't pause).\n"
			+ "• [b]Heat[/b] — each ejection adds 25. Dissipates 15/s. If an ejection would exceed 100 → MISFIRE.\n\n"
			+ "[b]Per ejection (click):[/b]\n"
			+ "• +15 charge · +25 heat · −$12,000 · +0.05 ε (launch stress)\n\n"
			+ "[b]Misfire (overload):[/b]\n"
			+ "• Lose 18 charge. Max 5 misfires before the launch aborts → base Sporulation with no bonus.\n\n"
			+ "[b]Optimal rhythm:[/b] eject → short pause → eject. Too fast → misfire. Too slow → charge decays and you never reach 100.\n\n"
			+ "[b]Success:[/b] Charge ≥ 100 → [b]BLACK PANSPERMIA[/b] (+10 LP). Requires Formed Mushroom for the ×3 spore bonus."
		),
		"unlock": {"type": "route_closed", "route": "PANSPERMIA NEGRA"},
		"see_also": ["primordio_mecanica", "esporulacion", "colonizacion_mecanica"],
	},
	"parasitismo": {
		"cat": "mutaciones",
		"name_es": "Parasitismo", "name_en": "Parasitism",
		"lore_prefix": "LORE_PARAS",
		"unlock": {"type": "route_closed", "route": "PARASITISMO"},
	},
	"hiperasimilacion": {
		"cat": "mutaciones",
		"name_es": "Hiperasimilación", "name_en": "Hyperassimilation",
		"lore_prefix": "LORE_HIPERAS",
		# Mecánica temprana de colapso; se revela tras la primera trascendencia.
		"unlock": {"type": "transcendence_count", "min": 1},
	},
	"colonizacion_mecanica": {
		"cat": "mutaciones",
		"name_es": "Colonización — Empuje de Frontera", "name_en": "Colonization — Frontier Push",
		"body_es": (
			"La mecánica activa de la fase inicial de Red Micelial. El micelio NO se llena solo: es un tira y afloja entre tus clicks y el entorno que retrocede.\n\n"
			+ "[b]Mecánica base:[/b]\n"
			+ "• Las hifas sostienen un piso de 8% de micelio (requiere ≥ 5 hifas). Por debajo de ese piso el micelio sube lento.\n"
			+ "• Por encima del piso: la frontera retrocede 2%/s automáticamente.\n"
			+ "• Cada click en el reactor aporta +1.2% de micelio.\n"
			+ "• No clickeás → el micelio cae y nunca llegarás a 60%.\n\n"
			+ "[b]Perturbaciones de retracción del sustrato:[/b]\n"
			+ "• Cada 14 s: el entorno muerde 4–18% de micelio (la mordida escala +0.05%/s con el tiempo en fase, tope 18%).\n"
			+ "• Cuanto más tarde en completar la fase, más dura la retracción.\n\n"
			+ "[b]Meta:[/b] Llegar al 60% de micelio. Al cruzar ese umbral mientras el Primordio no esté activo → activa PRIMORDIO (embrión del cuerpo fructífero)."
		),
		"body_en": (
			"The active mechanic of the first Red Micelial phase. Mycelium does NOT fill itself: it's a tug-of-war between your clicks and a retreating environment.\n\n"
			+ "[b]Base mechanic:[/b]\n"
			+ "• Hyphae sustain an 8% mycelium floor (requires ≥ 5 hyphae). Below that floor mycelium rises slowly.\n"
			+ "• Above the floor: the frontier recedes 2%/s automatically.\n"
			+ "• Each click on the reactor adds +1.2% mycelium.\n"
			+ "• No clicking → mycelium drops and you'll never reach 60%.\n\n"
			+ "[b]Substrate retraction events:[/b]\n"
			+ "• Every 14 s: the environment bites 4–18% mycelium (bite scales +0.05%/s with time in phase, cap 18%).\n"
			+ "• The longer you take, the harder the retraction hits.\n\n"
			+ "[b]Goal:[/b] Reach 60% mycelium. Crossing that threshold while Primordium is inactive → activates PRIMORDIUM (fruiting body embryo)."
		),
		"unlock": {"type": "route_closed", "route": "ESPORULACIÓN"},
		"see_also": ["primordio_mecanica", "red_micelial", "perturbaciones"],
	},
	"primordio_mecanica": {
		"cat": "mutaciones",
		"name_es": "Primordio — Maduración del Cuerpo Fructífero", "name_en": "Primordium — Fruiting Body Maturation",
		"body_es": (
			"Fase 2 de la Rama Verde. El embrión fúngico madura si mantenés el estrés dentro de una banda térmica. La biomasa es finita: NO regenera mientras el Primordio esté activo.\n\n"
			+ "[b]Banda de incubación:[/b] ε entre 0.30 y 0.50\n"
			+ "• Dentro de banda: la maduración progresa (meta: 60 s continuos en banda)\n"
			+ "• Por encima de 0.50: SOBRECALENTAMIENTO — drena 4 integridad/s y congela la maduración\n\n"
			+ "[b]Integridad del primordio:[/b] comienza en 100\n"
			+ "• Contaminación cada 6 s: daña 14–30 integridad (escala con tiempo madurando, cap 30) + patea ε +0.16 sacándote de banda\n"
			+ "• Si la integridad llega a 0 → el primordio muere\n\n"
			+ "[b]Acción «Regar»:[/b]\n"
			+ "• Costo: 2 biomasa (la reserva es finita, no regenera durante esta fase)\n"
			+ "• Restaura 18 integridad + enfría ε 0.10 hacia 0.30 (devuelve a la banda)\n"
			+ "• Sin cooldown: el límite es la biomasa disponible\n\n"
			+ "[b]Meta:[/b] Acumular 60 s dentro de banda sin romper la integridad → [b]Seta formada[/b]. La Seta Formada habilita Esporulación y desbloquea la ruta a Panspermia Negra con bonus ×3 de esporas."
		),
		"body_en": (
			"Phase 2 of the Green Branch. The fungal embryo matures if you keep stress within a thermal band. Biomass is finite: it does NOT regenerate while Primordium is active.\n\n"
			+ "[b]Incubation band:[/b] ε between 0.30 and 0.50\n"
			+ "• Inside band: maturation progresses (goal: 60 continuous seconds in band)\n"
			+ "• Above 0.50: OVERHEATING — drains 4 integrity/s and freezes maturation\n\n"
			+ "[b]Primordium integrity:[/b] starts at 100\n"
			+ "• Contamination every 6 s: deals 14–30 integrity damage (scales with maturation time, cap 30) + kicks ε +0.16 pushing you out of band\n"
			+ "• If integrity hits 0 → primordium dies\n\n"
			+ "[b]«Water» action:[/b]\n"
			+ "• Cost: 2 biomass (the pool is finite, does not regenerate during this phase)\n"
			+ "• Restores 18 integrity + cools ε by 0.10 toward 0.30 (returns to band)\n"
			+ "• No cooldown: the limit is available biomass\n\n"
			+ "[b]Goal:[/b] Accumulate 60 s inside band without breaking integrity → [b]Mushroom formed[/b]. Formed Mushroom enables Sporulation and unlocks the path to Black Panspermia with ×3 spore bonus."
		),
		"unlock": {"type": "route_closed", "route": "ESPORULACIÓN"},
		"see_also": ["colonizacion_mecanica", "panspermia", "esporulacion", "perturbaciones"],
	},
	"red_micelial": {
		"cat": "mutaciones",
		"name_es": "Red Micelial", "name_en": "Mycelial Network",
		"body_es": (
			"La rama biológica del árbol evolutivo. Activa la expansión del micelio como sistema vivo en lugar de la economía estructural.\n"
			+ "Bifurca en Colonización (empuje de frontera → Esporulación → Panspermia) y Simbiosis Mecánica (sincronización → Singularidad).\n"
			+ "Es anti-AFK: cada sub-fase exige acción concreta (regar el primordio, cargar la panspermia, sostener la sincronización)."
		),
		"body_en": (
			"The biological branch of the evolution tree. Activates mycelium expansion as a living system instead of structural economy.\n"
			+ "Forks into Colonization (frontier push → Sporulation → Panspermia) and Mechanical Symbiosis (sync → Singularity).\n"
			+ "Anti-AFK: each sub-phase demands concrete action (water the primordium, charge panspermia, sustain the sync)."
		),
		"unlock": {"type": "transcendence_count", "min": 1},
		"see_also": ["colonizacion_mecanica", "primordio_mecanica", "panspermia", "perturbaciones"],
	},

	"nucleo_conciencia": {
		"cat": "mutaciones",
		"name_es": "Núcleo de Conciencia", "name_en": "Consciousness Core",
		"body_es": (
			"Hito final de la rama azul (Simbiosis Mecánica). Integración de cómputo: una vez estabilizado el sistema, se sincronizan ciclos manualmente hasta encender el núcleo.\n\n"
			+ "Sincronización: el medidor sube solo mientras se cumplen TODAS las condiciones de fase a la vez — Contabilidad ≥ 3, Ω ≥ 0.55, ε entre 0.10 y 0.22, biomasa ≥ 6. Romper cualquiera lo hace caer.\n"
			+ "Encender el núcleo abre la ruta hacia SINGULARIDAD."
		),
		"body_en": (
			"Final milestone of the blue branch (Mechanical Symbiosis). Compute integration: once the system is stabilized, cycles are synced manually until the core ignites.\n\n"
			+ "Sync: the meter only rises while ALL phase conditions hold at once — Accounting ≥ 3, Ω ≥ 0.55, ε between 0.10 and 0.22, biomass ≥ 6. Breaking any one drops it.\n"
			+ "Igniting the core opens the path to SINGULARITY."
		),
		"unlock": {"type": "route_closed", "route": "SINGULARIDAD"},
		"see_also": ["simbiosis", "singularidad", "mente_colmena"],
	},

	# ── RUTAS ────────────────────────────────────────────────────────────────
	"depredador": {
		"cat": "rutas",
		"name_es": "Depredador de Realidades", "name_en": "Reality Predator",
		"body_es": (
			"Se activa cuando la economía entra en crisis profunda (estrés alto, sin flujo activo).\n"
			+ "El organismo devora sus propios upgrades para generar dinero. Tiene un timer de inestabilidad: si llega a cero → COLAPSO DEPREDATORIO.\n"
			+ "Si consumís TODOS los upgrades antes del colapso → DEPREDADOR DE REALIDADES (final exitoso). Desde ahí se puede sellar MET.OSCURO."
		),
		"body_en": (
			"Activates when the economy enters deep crisis (high stress, no active flow).\n"
			+ "The organism devours its own upgrades to generate money. Has an instability timer: if it hits zero → PREDATORY COLLAPSE.\n"
			+ "Consume ALL upgrades before collapse → PREDATOR OF REALITIES (success ending). From there you can seal DARK MET."
		),
		"unlock": {"type": "always"},
	},
	"met_oscuro": {
		"cat": "rutas",
		"name_es": "Metabolismo Oscuro", "name_en": "Dark Metabolism",
		"lore_prefix": "LORE_MO",
		"see_also": ["depredador", "esclerocio", "autofagia", "necrosis", "omega_cero", "remision"],
		"body_es": (
			"Se sella durante una run de Depredador cuando se cumplen condiciones críticas (dinero bajo + devours + biomasa).\n"
			+ "Reemplaza la economía estándar con bioquímica no documentada: upgrades bloqueados, devorado pasivo continuo.\n"
			+ "El cierre normal es METABOLISMO OSCURO (saturación de biomasa). Con el acceso comprado, se pueden activar sub-rutas."
		),
		"body_en": (
			"Sealed during a Predator run when critical conditions are met (low money + devours + biomass).\n"
			+ "Replaces standard economy with undocumented biochemistry: upgrades locked, continuous passive devouring.\n"
			+ "Default close is DARK METABOLISM (biomass saturation). With access purchased, sub-routes can be activated."
		),
		"unlock": {"type": "transcendence_count", "min": 1},
	},
	"post_tras_routes": {
		"cat": "rutas",
		"name_es": "Rutas Post-Trascendencia", "name_en": "Post-Transcendence Routes",
		"body_es": (
			"Al trascender (completar ciertos finales y tener PL invertido), se puede elegir una ruta especial para la próxima run.\n"
			+ "Vacío Hambriento: multiplicador de producción creciente, sin flujo manual.\n"
			+ "Carnaval de Mutaciones: rota mutaciones activas cada pocos segundos.\n"
			+ "Reencarnación Heredada: upgrades del ciclo anterior persisten, pero con costo inflado (×1.5 por nivel)."
		),
		"body_en": (
			"On transcendence (completing certain endings with LP invested), a special route can be chosen for the next run.\n"
			+ "Hungry Void: growing production multiplier, no manual flow.\n"
			+ "Mutation Carnival: rotates active mutations every few seconds.\n"
			+ "Inherited Reincarnation: prior cycle upgrades persist, but with inflated cost (×1.5 per level)."
		),
		"unlock": {"type": "transcendence_count", "min": 1},
		"see_also": ["vacio_hambriento", "carnaval", "reencarnacion"],
	},
	"vacio_hambriento": {
		"cat": "rutas",
		"name_es": "Vacío Hambriento", "name_en": "Hungry Void",
		"body_es": (
			"Ruta post-trascendencia. Consume permanentemente TODOS tus buffs cósmicos activos; a cambio, la producción es ×100 durante toda la run.\n\n"
			+ "Sin flujo manual: el sistema produce solo. Sostener la renuncia (sin clickear) durante 300 s con $10M alcanzados solo por clicks previos abre el final ASCESIS PROFUNDA.\n\n"
			+ "[i]Apuesta de todo o nada: sacrificás la meta-progresión cósmica por un pico brutal de una sola run.[/i]"
		),
		"body_en": (
			"Post-transcendence route. Permanently consumes ALL your active cosmic buffs; in exchange, production is ×100 for the whole run.\n\n"
			+ "No manual flow: the system produces on its own. Sustaining renunciation (no clicking) for 300 s with $10M reached by prior clicks opens the DEEP ASCESIS ending.\n\n"
			+ "[i]All-or-nothing bet: you sacrifice cosmic meta-progression for one brutal run spike.[/i]"
		),
		"unlock": {"type": "transcendence_count", "min": 1},
		"see_also": ["ascesis_profunda", "post_tras_routes"],
	},
	"carnaval": {
		"cat": "rutas",
		"name_es": "Carnaval de Mutaciones", "name_en": "Mutation Carnival",
		"body_es": (
			"Ruta post-trascendencia. Al iniciar se eligen 3 mutaciones aleatorias que rotan automáticamente cada 60 s, sin control manual.\n\n"
			+ "Dos finales posibles:\n"
			+ "• POLIMORFÍA TOTAL — sobrevivir 12 rotaciones manteniendo Bio ≥ 8, Ω ≥ 0.35 y $ ≥ 300K.\n"
			+ "• DOMADOR DEL CAOS — acumular suficiente poder económico ($ en millones) a través del caos."
		),
		"body_en": (
			"Post-transcendence route. At start, 3 random mutations are chosen and rotate automatically every 60 s, with no manual control.\n\n"
			+ "Two possible endings:\n"
			+ "• TOTAL POLYMORPHIA — survive 12 rotations holding Bio ≥ 8, Ω ≥ 0.35 and $ ≥ 300K.\n"
			+ "• CHAOS TAMER — accumulate enough economic power ($ in millions) through the chaos."
		),
		"unlock": {"type": "transcendence_count", "min": 1},
		"see_also": ["polimorfia_total", "domador_caos", "post_tras_routes"],
	},
	"reencarnacion": {
		"cat": "rutas",
		"name_es": "Reencarnación Heredada", "name_en": "Inherited Reincarnation",
		"body_es": (
			"Ruta post-trascendencia. Empezás con todos los upgrades al nivel del ciclo anterior, pero cada compra futura escala ×1.5 más caro (deuda kármica).\n\n"
			+ "[i]Arrancás fortísimo, pero el techo llega antes: el crecimiento se ahoga en su propia herencia.[/i]"
		),
		"body_en": (
			"Post-transcendence route. You start with all upgrades at the previous cycle's level, but every future purchase scales ×1.5 more expensive (karmic debt).\n\n"
			+ "[i]You start extremely strong, but the ceiling comes sooner: growth drowns in its own inheritance.[/i]"
		),
		"unlock": {"type": "transcendence_count", "min": 1},
		"see_also": ["post_tras_routes"],
	},

	# ── ÁRBOL OSCURO ─────────────────────────────────────────────────────────
	"esclerocio": {
		"cat": "arbol_oscuro",
		"name_es": "Esclerocio Oscuro", "name_en": "Dark Sclerotium",
		"lore_prefix": "LORE_ESCLEROCIO",
		"see_also": ["met_oscuro", "panspermia", "cross_semilla"],
		"body_es": (
			"El hongo se encapsula voluntariamente en una estructura dura: el esclerocio. Cierra la run con intención.\n"
			+ "Activa el sistema de Memoria Oscura: +13% biomasa y -10% umbral MO en TODAS las runs siguientes hasta que germine.\n"
			+ "Germina al cerrar PANSPERMIA NEGRA → desbloquea el legado semilla_cosmica_oscura permanentemente.\n"
			+ "Requisito: comprar 'Acceso: Esclerocio Oscuro' en el Banco Genético (30 PL, T≥1)."
		),
		"body_en": (
			"The fungus voluntarily encapsulates into a hard structure: the sclerotium. Closes the run intentionally.\n"
			+ "Activates Dark Memory: +13% biomass and -10% MO threshold in ALL subsequent runs until it germinates.\n"
			+ "Germinates when BLACK PANSPERMIA closes → permanently unlocks the dark_seed_cosmic legacy.\n"
			+ "Requirement: buy 'Access: Dark Sclerotium' in Genetic Bank (30 LP, T≥1)."
		),
		"unlock": {"type": "transcendence_count", "min": 1},
	},
	"autofagia": {
		"cat": "arbol_oscuro",
		"name_es": "Autofagia Necrótica", "name_en": "Necrotic Autophagy",
		"see_also": ["met_oscuro", "depredador", "omega_cero", "cross_ciclo"],
		"body_es": (
			"El organismo comienza a digerir sus propias estructuras de forma controlada. Irreversible.\n"
			+ "Genera bursts de dinero al devorar upgrades. Con suficientes devours, se puede colapsar manualmente para el cierre.\n"
			+ "Requisito: comprar 'Acceso: Autofagia Necrótica' (50 PL, requiere DEPREDADOR DE REALIDADES completado)."
		),
		"body_en": (
			"The organism begins digesting its own structures in a controlled way. Irreversible.\n"
			+ "Generates money bursts when devouring upgrades. With enough devours, can manually collapse to close.\n"
			+ "Requirement: buy 'Access: Necrotic Autophagy' (50 LP, requires PREDATOR OF REALITIES completed)."
		),
		"unlock": {"type": "route_closed", "route": "DEPREDADOR DE REALIDADES"},
	},
	"necrosis": {
		"cat": "arbol_oscuro",
		"name_es": "Necrosis Controlada", "name_en": "Controlled Necrosis",
		"lore_prefix": "LORE_NECROSIS",
		"see_also": ["met_oscuro", "omega_cero", "cross_plasticidad"],
		"body_es": (
			"Doble economía: dinero estándar + Necromasa (Ν). La Ν se genera por clicks y pasivos, se gasta en Agentes Necróticos.\n"
			+ "Cada Agente empuja Ω hacia un floor cada vez más bajo. Al alcanzar el floor → cierre NECROSIS CONTROLADA.\n"
			+ "Requisito: comprar 'Acceso: Necrosis Controlada' (50 PL, requiere cualquier final de Met. Oscuro completado)."
		),
		"body_en": (
			"Dual economy: standard money + Necromass (Ν). Ν is generated by clicks and passives, spent on Necrotic Agents.\n"
			+ "Each Agent pushes Ω toward an ever-lower floor. Reaching the floor → CONTROLLED NECROSIS close.\n"
			+ "Requirement: buy 'Access: Controlled Necrosis' (50 LP, requires any Dark Met. ending completed)."
		),
		"unlock": {"type": "route_closed_any", "routes": ["METABOLISMO OSCURO", "ESCLEROCIO OSCURO", "AUTOFAGIA NECRÓTICA"]},
	},
	"omega_cero": {
		"cat": "arbol_oscuro",
		"name_es": "Protocolo Omega-Cero", "name_en": "Omega-Zero Protocol",
		"lore_prefix": "LORE_OMEGA_CERO",
		"see_also": ["autofagia", "necrosis", "esclerocio", "remision", "cross_sintesis"],
		"body_es": (
			"La síntesis de las tres muertes: devour (autofagia) + Ω-combustible (necrosis) + sello intencional (esclerocio).\n"
			+ "Genera Φ con cada devour; a menor Ω, mayor Φ (hasta ×10). Al alcanzar Φ objetivo → sello del protocolo.\n"
			+ "Requiere comprar 'Protocolo Omega-Cero' (100 PL, T≥2, las 3 sub-rutas completadas). Final del árbol oscuro."
		),
		"body_en": (
			"Synthesis of three deaths: devour (autophagy) + Ω-fuel (necrosis) + intentional seal (sclerotium).\n"
			+ "Generates Φ with each devour; lower Ω = more Φ (up to ×10). Reaching Φ target → seal the protocol.\n"
			+ "Requires 'Omega-Zero Protocol' buff (100 LP, T≥2, all 3 sub-routes completed). End of dark tree."
		),
		"unlock": {"type": "route_closed_all", "routes": ["AUTOFAGIA NECRÓTICA", "NECROSIS CONTROLADA", "ESCLEROCIO OSCURO"]},
	},
	"remision": {
		"cat": "arbol_oscuro",
		"name_es": "Remisión Metabólica", "name_en": "Metabolic Remission",
		"lore_prefix": "LORE_REMISION",
		"see_also": ["omega_cero", "cross_sintesis"],
		"body_es": (
			"Después de aprender todas las formas de morir, el organismo aprende a sanar.\n"
			+ "Combate entre el organismo sanador y la enfermedad residual de Met. Oscuro. La biomasa sube y la Ω se recupera.\n"
			+ "Requiere 'Remisión Metabólica' en el Banco (15 PL, las 4 sub-rutas previas completadas). Final último del árbol."
		),
		"body_en": (
			"After learning all ways to die, the organism learns to heal.\n"
			+ "Battle between healing organism and residual Dark Met. disease. Biomass rises and Ω recovers.\n"
			+ "Requires 'Metabolic Remission' buff (15 LP, all 4 prior sub-routes completed). Final dark tree ending."
		),
		"unlock": {"type": "route_closed", "route": "PROTOCOLO OMEGA-CERO"},
	},

	# ── FINALES (cierres especiales — colapsos y finales de ruta) ──────────────
	"colapso_depredatorio": {
		"cat": "finales",
		"name_es": "Colapso Depredatorio", "name_en": "Predatory Collapse",
		"body_es": (
			"Final de fracaso del Depredador de Realidades. El timer de inestabilidad llega a cero sin que sellaras Metabolismo Oscuro ni consumieras toda la realidad.\n\n"
			+ "Ni domesticado ni consumado: la inestabilidad estructural implosiona el sistema.\n\n"
			+ "Otorga +8 PL (el caos también deja legado).\n"
			+ "[i]\"El Depredador no se estabilizó a tiempo: la inestabilidad estructural implosiona el sistema.\"[/i]"
		),
		"body_en": (
			"Failure ending of the Reality Predator. The instability timer hits zero without you sealing Dark Metabolism or consuming all of reality.\n\n"
			+ "Neither tamed nor consummated: structural instability implodes the system.\n\n"
			+ "Grants +8 LP (chaos leaves a legacy too).\n"
			+ "[i]\"The Predator never stabilized in time: structural instability implodes the system.\"[/i]"
		),
		"unlock": {"type": "route_closed", "route": "COLAPSO DEPREDATORIO"},
		"see_also": ["depredador", "met_oscuro"],
	},
	"colapso_controlado": {
		"cat": "finales",
		"name_es": "Colapso Controlado", "name_en": "Controlled Collapse",
		"body_es": (
			"Final desbloqueado por la Fractura Epistémica (Banco Cósmico, Tier 3). Canaliza la Hiperasimilación en un colapso dirigido en vez de una implosión.\n\n"
			+ "Disponible cuando ε > 0.90 y Ω > 0.30: cerrás la run de forma controlada con +6 PL y el reactor se vuelve dorado.\n\n"
			+ "[i]\"La bioquímica no documentada se canaliza en colapso controlado. El reactor se volvió dorado.\"[/i]"
		),
		"body_en": (
			"Ending unlocked by Epistemic Fracture (Cosmic Bank, Tier 3). Channels Hyperassimilation into a directed collapse instead of an implosion.\n\n"
			+ "Available when ε > 0.90 and Ω > 0.30: you close the run in a controlled way for +6 LP and the reactor turns gold.\n\n"
			+ "[i]\"Hyperassimilation channeled into a controlled collapse. The reactor turned gold.\"[/i]"
		),
		"unlock": {"type": "route_closed", "route": "COLAPSO CONTROLADO"},
		"see_also": ["hiperasimilacion", "cosmica_buffs"],
	},
	"colapso_sintetico": {
		"cat": "finales",
		"name_es": "Colapso Sintético", "name_en": "Synthetic Collapse",
		"body_es": (
			"Final de fracaso del Protocolo Omega-Cero. Si la síntesis se queda sin material para devorar, la Φ se agota por inanición y el núcleo colapsa antes de alcanzar el sello.\n\n"
			+ "No otorga el PL del sello: la síntesis exige alimentar el loop activamente.\n\n"
			+ "[i]Tocar el borde de Ω = 0 sin completar la síntesis tiene un precio.[/i]"
		),
		"body_en": (
			"Failure ending of the Omega-Zero Protocol. If the synthesis runs out of material to devour, Φ starves and the core collapses before reaching the seal.\n\n"
			+ "It does not grant the seal's LP: the synthesis demands actively feeding the loop.\n\n"
			+ "[i]Touching the Ω = 0 edge without completing the synthesis has a price.[/i]"
		),
		"unlock": {"type": "route_closed", "route": "COLAPSO SINTÉTICO"},
		"see_also": ["omega_cero"],
	},
	"ascesis_profunda": {
		"cat": "finales",
		"name_es": "Ascesis Profunda", "name_en": "Deep Ascesis",
		"body_es": (
			"Final de la ruta Vacío Hambriento. Tras renunciar a los buffs cósmicos, sostenés la renuncia: $10M alcanzados SOLO por clicks y 300 s sin volver a clickear.\n\n"
			+ "Otorga +7 PL.\n"
			+ "[i]\"La renuncia absoluta genera más estabilidad que cualquier acumulación.\"[/i]"
		),
		"body_en": (
			"Ending of the Hungry Void route. After renouncing cosmic buffs, you sustain the renunciation: $10M reached by clicks ALONE and 300 s without clicking again.\n\n"
			+ "Grants +7 LP.\n"
			+ "[i]\"Absolute renunciation generates more stability than any accumulation.\"[/i]"
		),
		"unlock": {"type": "route_closed", "route": "ASCESIS_PROFUNDA"},
		"see_also": ["vacio_hambriento"],
	},
	"polimorfia_total": {
		"cat": "finales",
		"name_es": "Polimorfía Total", "name_en": "Total Polymorphia",
		"body_es": (
			"Final de la ruta Carnaval de Mutaciones. Sobrevivís 12 rotaciones de mutación manteniendo simultáneamente Bio ≥ 8.0, Ω ≥ 0.35 y $ ≥ 300K.\n\n"
			+ "Otorga +9 PL.\n"
			+ "[i]\"El hongo absorbió 12 ciclos mutacionales — su identidad trasciende toda clasificación.\"[/i]"
		),
		"body_en": (
			"Ending of the Mutation Carnival route. You survive 12 mutation rotations holding Bio ≥ 8.0, Ω ≥ 0.35 and $ ≥ 300K simultaneously.\n\n"
			+ "Grants +9 LP.\n"
			+ "[i]\"The fungus absorbed 12 mutational cycles — its identity transcends all classification.\"[/i]"
		),
		"unlock": {"type": "route_closed", "route": "POLIMORFÍA TOTAL"},
		"see_also": ["carnaval"],
	},
	"domador_caos": {
		"cat": "finales",
		"name_es": "Domador del Caos", "name_en": "Chaos Tamer",
		"body_es": (
			"Final alternativo de la ruta Carnaval de Mutaciones. En vez de sostener las condiciones de Polimorfía, domás el caos acumulando un gran poder económico (millones de $) a través de las rotaciones.\n\n"
			+ "Otorga +11 PL.\n"
			+ "[i]\"Domó el caos mutacional acumulando millones de poder económico.\"[/i]"
		),
		"body_en": (
			"Alternative ending of the Mutation Carnival route. Instead of holding Polymorphia's conditions, you tame the chaos by accumulating great economic power (millions of $) through the rotations.\n\n"
			+ "Grants +11 LP.\n"
			+ "[i]\"Tamed the mutational chaos accumulating millions of economic power.\"[/i]"
		),
		"unlock": {"type": "route_closed", "route": "DOMADOR DEL CAOS"},
		"see_also": ["carnaval"],
	},

	# ── CRUCES DE LEGADO (legados permanentes por cruzar dos rutas) ────────────
	# Se revelan vía flags persistentes que marca RunManager al cruzar las rutas.
	"cross_semilla": {
		"cat": "cruces",
		"name_es": "Semilla Cósmica Oscura", "name_en": "Dark Cosmic Seed",
		"body_es": (
			"Cruce ESCLEROCIO OSCURO → PANSPERMIA NEGRA.\n"
			+ "Sembrás la Memoria Oscura con un Esclerocio y luego la hacés germinar cerrando por Panspermia Negra.\n\n"
			+ "Legado permanente: producción pasiva ×3."
		),
		"body_en": (
			"Cross DARK SCLEROTIUM → BLACK PANSPERMIA.\n"
			+ "Seed Dark Memory with a Sclerotium, then germinate it by closing via Black Panspermia.\n\n"
			+ "Permanent legacy: passive production ×3."
		),
		"unlock": {"type": "legacy_flag", "flag": "esclerocio_panspermia_done"},
		"see_also": ["esclerocio", "panspermia"],
	},
	"cross_ciclo": {
		"cat": "cruces",
		"name_es": "Ciclo Catabólico", "name_en": "Catabolic Cycle",
		"body_es": (
			"Cruce AUTOFAGIA NECRÓTICA → DEPREDADOR DE REALIDADES.\n"
			+ "El organismo que aprendió a digerirse lleva ese hambre al frenesí depredatorio.\n\n"
			+ "Legado permanente: todos los devours liberan ×1.5 biomasa."
		),
		"body_en": (
			"Cross NECROTIC AUTOPHAGY → PREDATOR OF REALITIES.\n"
			+ "The organism that learned to digest itself carries that hunger into the predatory frenzy.\n\n"
			+ "Permanent legacy: all devours release ×1.5 biomass."
		),
		"unlock": {"type": "legacy_flag", "flag": "autofagia_depredador_done"},
		"see_also": ["autofagia", "depredador"],
	},
	"cross_plasticidad": {
		"cat": "cruces",
		"name_es": "Plasticidad Terminal", "name_en": "Terminal Plasticity",
		"body_es": (
			"Cruce HOMEORRESIS → NECROSIS CONTROLADA.\n"
			+ "Dominaste la estabilidad máxima Y el colapso total: los dos bordes de Ω son el mismo.\n\n"
			+ "Legado permanente: ×1.5 ingresos (click y pasivo) cuando Ω > 0.55 o Ω < 0.10."
		),
		"body_en": (
			"Cross HOMEORHESIS → CONTROLLED NECROSIS.\n"
			+ "You mastered maximum stability AND total collapse: both edges of Ω are the same.\n\n"
			+ "Permanent legacy: ×1.5 income (click and passive) when Ω > 0.55 or Ω < 0.10."
		),
		"unlock": {"type": "legacy_flag", "flag": "homeorhesis_necrosis_done"},
		"see_also": ["homeorhesis", "necrosis"],
	},
	"cross_sintesis": {
		"cat": "cruces",
		"name_es": "Síntesis Vital", "name_en": "Vital Synthesis",
		"body_es": (
			"Cruce PROTOCOLO OMEGA-CERO ↔ REMISIÓN METABÓLICA (cualquier orden).\n"
			+ "Tocaste el piso absoluto de Ω Y la abundancia máxima de biomasa: colapso y crecimiento son el mismo borde.\n\n"
			+ "Legado permanente: ×2 ingresos cuando Ω < 0.20 y biomasa ≥ 80."
		),
		"body_en": (
			"Cross OMEGA-ZERO PROTOCOL ↔ METABOLIC REMISSION (either order).\n"
			+ "You touched Ω's absolute floor AND biomass's maximum abundance: collapse and growth are the same edge.\n\n"
			+ "Permanent legacy: ×2 income when Ω < 0.20 and biomass ≥ 80."
		),
		"unlock": {"type": "legacy_flag", "flag": "omega_remision_done"},
		"see_also": ["omega_cero", "remision"],
	},

	# ── CAPA CÓSMICA (meta-progresión sobre la trascendencia) ──────────────────
	"cosmica_intro": {
		"cat": "cosmica",
		"name_es": "Esencia y Banco Cósmico", "name_en": "Essence & Cosmic Bank",
		"body_es": (
			"Al trascender ganás Esencia (Ξ), una moneda que persiste entre trascendencias y se gasta en el Banco Cósmico — la capa de mejoras permanentes por encima del Banco Genético.\n\n"
			+ "Esencia ganada = PL/10 + finales_únicos × 5 + trascendencias × 2.\n"
			+ "Los buffs cósmicos afectan TODAS las runs futuras, sin importar la ruta."
		),
		"body_en": (
			"On transcending you earn Essence (Ξ), a currency that persists across transcendences and is spent in the Cosmic Bank — the permanent upgrade layer above the Genetic Bank.\n\n"
			+ "Essence gained = LP/10 + unique_endings × 5 + transcendences × 2.\n"
			+ "Cosmic buffs affect ALL future runs, regardless of route."
		),
		"unlock": {"type": "transcendence_count", "min": 1},
		"see_also": ["sym_meta", "cosmica_buffs"],
	},
	"cosmica_buffs": {
		"cat": "cosmica",
		"name_es": "Buffs Cósmicos", "name_en": "Cosmic Buffs",
		"body_es": (
			"Compras del Banco Cósmico (costo en Esencia Ξ), por tier:\n\n"
			+ "[b]Tier 1[/b]\n"
			+ "• Impulso Inicial (6) — empezás con $500 generados\n"
			+ "• Omega Primordial (8) — Ω_min +0.05 permanente\n"
			+ "• Resonancia Biótica (10) — biomasa inicial 1.5\n"
			+ "• Deflación Cósmica (12) — −8% escalado de precios\n"
			+ "• Eco de Legado (15) — +5 PL al inicio de cada run\n"
			+ "• Latencia Hifal (12) — piso de hifas: biomasa y ε despiertan al instante\n\n"
			+ "[b]Tier 2[/b]\n"
			+ "• Árbol Acelerado (18) — timers MET.OSCURO/DEPREDADOR −40%\n"
			+ "• Memoria de Recurso Cósmica (20) — primeras 2 compras gratis por upgrade\n"
			+ "• Memoria Persistente (22) — 1er nivel de Contabilidad y Trueque gratis\n"
			+ "• Cicatriz Metabólica (25) — tiempo para Homeorresis a la mitad\n"
			+ "• Convergencia Cíclica (28) — +5% ingresos por trascendencia acumulada\n"
			+ "• Reserva Nutricia (18) — +60 nutrientes al inicio de cada run\n\n"
			+ "[b]Tier 3[/b]\n"
			+ "• Fractura Epistémica (35) — desbloquea ruta COLAPSO CONTROLADO\n"
			+ "• Sustrato Cósmico (50) — próxima trascendencia da Ξ ×2 (un uso)\n"
			+ "• Resonancia Perpetua (60) — +25% Esencia permanente al trascender"
		),
		"body_en": (
			"Cosmic Bank purchases (cost in Essence Ξ), by tier:\n\n"
			+ "[b]Tier 1[/b]\n"
			+ "• Initial Boost (6) — start with $500 generated\n"
			+ "• Primordial Omega (8) — permanent Ω_min +0.05\n"
			+ "• Biotic Resonance (10) — starting biomass 1.5\n"
			+ "• Cosmic Deflation (12) — −8% price scaling\n"
			+ "• Legacy Echo (15) — +5 LP at the start of each run\n"
			+ "• Hyphal Latency (12) — hyphae floor: biomass and ε wake instantly\n\n"
			+ "[b]Tier 2[/b]\n"
			+ "• Accelerated Tree (18) — DARK MET./PREDATOR timers −40%\n"
			+ "• Cosmic Resource Memory (20) — first 2 buys free per upgrade\n"
			+ "• Persistent Memory (22) — 1st Accounting and Barter level free\n"
			+ "• Metabolic Scar (25) — Homeorhesis time halved\n"
			+ "• Cyclic Convergence (28) — +5% income per accumulated transcendence\n"
			+ "• Nutrient Reserve (18) — +60 nutrients at the start of each run\n\n"
			+ "[b]Tier 3[/b]\n"
			+ "• Epistemic Fracture (35) — unlocks CONTROLLED COLLAPSE route\n"
			+ "• Cosmic Substrate (50) — next transcendence grants Ξ ×2 (one use)\n"
			+ "• Perpetual Resonance (60) — +25% permanent Essence on transcending"
		),
		"unlock": {"type": "transcendence_count", "min": 1},
		"see_also": ["cosmica_intro"],
	},

	# ── VALORES (hojas de referencia rápida; números reales de Balance.gd) ──────
	"ref_umbrales": {
		"cat": "valores",
		"name_es": "Umbrales de rutas oscuras", "name_en": "Dark route thresholds",
		"body_es": (
			"Condiciones para activar/sellar cada ruta dentro de Metabolismo Oscuro:\n\n"
			+ "• Sellar MET. OSCURO: 10 devours + biomasa ≥ 50 + 15 s de activación\n"
			+ "• Esclerocio: 30 devours + biomasa ≥ 50 + ε < 0.25\n"
			+ "• Autofagia: biomasa ≥ 50 + 5 niveles de upgrade disponibles\n"
			+ "• Necrosis: biomasa ≥ 50 + Δ$ ≥ 200/s (economía activa)\n"
			+ "• Omega-Cero: T ≥ 2 + buff comprado + biomasa ≥ 50 + 5 devours · sello a Φ 300\n"
			+ "• Remisión: biomasa ≥ 150 en MO · sello tras 60 s dentro de banda de Ω"
		),
		"body_en": (
			"Conditions to activate/seal each route inside Dark Metabolism:\n\n"
			+ "• Seal DARK MET.: 10 devours + biomass ≥ 50 + 15 s activation\n"
			+ "• Sclerotium: 30 devours + biomass ≥ 50 + ε < 0.25\n"
			+ "• Autophagy: biomass ≥ 50 + 5 available upgrade levels\n"
			+ "• Necrosis: biomass ≥ 50 + Δ$ ≥ 200/s (active economy)\n"
			+ "• Omega-Zero: T ≥ 2 + bought buff + biomass ≥ 50 + 5 devours · seal at Φ 300\n"
			+ "• Remission: biomass ≥ 150 in MO · seal after 60 s inside Ω band"
		),
		"unlock": {"type": "transcendence_count", "min": 1},
	},
	"ref_accesos": {
		"cat": "valores",
		"name_es": "Costos del Banco — Árbol Oscuro", "name_en": "Bank costs — Dark Tree",
		"body_es": (
			"Compras del Banco Genético que habilitan las rutas oscuras (PL = Poder Latente):\n\n"
			+ "• Acceso: Esclerocio Oscuro — 30 PL (tras T ≥ 1)\n"
			+ "• Acceso: Autofagia Necrótica — 50 PL (Depredador de Realidades cerrado)\n"
			+ "• Acceso: Necrosis Controlada — 50 PL (cualquier final de Met. Oscuro)\n"
			+ "• Protocolo Omega-Cero — 100 PL (T ≥ 2 + las 3 sub-rutas cerradas)\n"
			+ "• Remisión Metabólica — 15 PL (las 4 sub-rutas oscuras cerradas)"
		),
		"body_en": (
			"Genetic Bank purchases that enable the dark routes (LP = Latent Power):\n\n"
			+ "• Access: Dark Sclerotium — 30 LP (after T ≥ 1)\n"
			+ "• Access: Necrotic Autophagy — 50 LP (Predator of Realities closed)\n"
			+ "• Access: Controlled Necrosis — 50 LP (any Dark Met. ending)\n"
			+ "• Omega-Zero Protocol — 100 LP (T ≥ 2 + the 3 sub-routes closed)\n"
			+ "• Metabolic Remission — 15 LP (all 4 dark sub-routes closed)"
		),
		"unlock": {"type": "transcendence_count", "min": 1},
	},
	"ref_multiplicadores": {
		"cat": "valores",
		"name_es": "Multiplicadores clave", "name_en": "Key multipliers",
		"body_es": (
			"• Nutrientes: −15% costo de upgrades por cada 50 (cap −45% a 150)\n"
			+ "• Vacío Hambriento: producción ×100\n"
			+ "• Reencarnación Heredada: costos de upgrade ×1.5\n"
			+ "• Necrosis: Ω como combustible, multiplicador hasta ×25\n"
			+ "• Omega-Cero: Φ por devour hasta ×10 (cuanto más bajo Ω, más Φ)\n"
			+ "• Memoria Oscura (Esclerocio): +15% biomasa · ε resiste 30% · −10% umbral MO\n"
			+ "• Semilla Cósmica Oscura: pasivo ×3 permanente (cruce Esclerocio → Panspermia)"
		),
		"body_en": (
			"• Nutrients: −15% upgrade cost per 50 (cap −45% at 150)\n"
			+ "• Hungry Void: production ×100\n"
			+ "• Inherited Reincarnation: upgrade costs ×1.5\n"
			+ "• Necrosis: Ω as fuel, multiplier up to ×25\n"
			+ "• Omega-Zero: Φ per devour up to ×10 (lower Ω, more Φ)\n"
			+ "• Dark Memory (Sclerotium): +15% biomass · ε resists 30% · −10% MO threshold\n"
			+ "• Dark Cosmic Seed: permanent ×3 passive (Sclerotium → Panspermia cross)"
		),
		"unlock": {"type": "always"},
	},
	"ref_pl_rutas": {
		"cat": "valores",
		"name_es": "PL base por ruta de cierre", "name_en": "Base LP per closing route",
		"body_es": (
			"PL otorgado al cerrar por cada ruta (antes del bonus NG+ variable):\n\n"
			+ "• Depredador de Realidades: 12 · Domador del Caos: 11 · Panspermia Negra: 10\n"
			+ "• Polimorfía Total: 9 · Homeorresis: 8 · Mente Colmena: 8\n"
			+ "• Omega-Cero: 8 · Remisión: 8 · Colapso Depredatorio: 8 · Ascesis Profunda: 7\n"
			+ "• Esclerocio: 6 · Autofagia: 6 · Colapso Controlado: 6\n"
			+ "• Necrosis: 5 · Esporulación: 5 · Allostasis: 4 · Simbiosis: 4 · Met. Oscuro: 4\n"
			+ "• Homeostasis: 3 · Parasitismo: 2 · Hiperasimilación: 1"
		),
		"body_en": (
			"LP granted on closing via each route (before the variable NG+ bonus):\n\n"
			+ "• Predator of Realities: 12 · Chaos Tamer: 11 · Black Panspermia: 10\n"
			+ "• Total Polymorphia: 9 · Homeorhesis: 8 · Hive Mind: 8\n"
			+ "• Omega-Zero: 8 · Remission: 8 · Predatory Collapse: 8 · Deep Ascesis: 7\n"
			+ "• Sclerotium: 6 · Autophagy: 6 · Controlled Collapse: 6\n"
			+ "• Necrosis: 5 · Sporulation: 5 · Allostasis: 4 · Symbiosis: 4 · Dark Met.: 4\n"
			+ "• Homeostasis: 3 · Parasitism: 2 · Hyperassimilation: 1"
		),
		"unlock": {"type": "transcendence_count", "min": 1},
	},
}
